export const BLOG_POSTS = [
  {
    slug: "best-earning-apps-pakistan-2026",
    title: "Best Earning Apps Pakistan 2026 — Top 10 Verified & Paying Real Money",
    excerpt: "We tested 60+ earning apps in Pakistan and ranked the top 10. Casino, color prediction, sports betting — all verified for EasyPaisa & JazzCash withdrawal. Your complete 2026 guide.",
    category: "Earning App Guide",
    keyword: "best earning apps pakistan 2026",
    date: "2026-05-09",
    readTime: "11 min read",
    image: "/images/screenshots/lucky-3.webp",
    imageAlt: "Best earning apps Pakistan 2026 top 10 real money verified",
  },
  {
    slug: "how-to-withdraw-jazzcash-easypaisa-pakistan",
    title: "How to Withdraw from Earning Apps to JazzCash & EasyPaisa Pakistan 2026",
    excerpt: "Step-by-step JazzCash and EasyPaisa withdrawal guide for Pakistani earning app players. Fix common errors, understand limits, and get your money out in minutes.",
    category: "How-To Guide",
    keyword: "how to withdraw jazzcash easypaisa earning apps pakistan",
    date: "2026-05-09",
    readTime: "9 min read",
    image: "/images/screenshots/color-1.webp",
    imageAlt: "How to withdraw to JazzCash EasyPaisa from earning apps Pakistan 2026",
  },
  {
    slug: "done999-review-pakistan",
    title: "Done999 APK Download Pakistan — Real or Fake 2026",
    excerpt: "Is Done999 real or fake? We tested it with real PKR, withdrew to JazzCash, and share everything — bonuses, risks, and our honest verdict for Pakistani players.",
    category: "App Review",
    keyword: "done999 real or fake pakistan",
    date: "2026-04-20",
    readTime: "9 min read",
    image: "/images/screenshots/done999-1.webp",
    imageAlt: "Done999 APK download screen showing color prediction interface Pakistan",
  },
  {
    slug: "663bet-apk-pakistan",
    title: "663Bet APK Pakistan Review — Legit or Scam 2026",
    excerpt: "Complete 663Bet review for Pakistani players. Download guide, welcome bonus walkthrough, withdrawal speed test, and our final verdict — is it worth your money?",
    category: "App Review",
    keyword: "663bet apk download pakistan",
    date: "2026-04-18",
    readTime: "8 min read",
    image: "/images/screenshots/lucky-3.webp",
    imageAlt: "663Bet APK casino interface Pakistan download guide 2026",
  },
  {
    slug: "color-prediction-game-pakistan",
    title: "What is Color Prediction Game Pakistan — How to Play and Win 2026",
    excerpt: "New to color prediction? This beginner's guide covers how it works, which apps are safe in Pakistan, basic strategy, and how to withdraw to JazzCash and EasyPaisa.",
    category: "Beginner Guide",
    keyword: "how to play color prediction pakistan",
    date: "2026-04-15",
    readTime: "10 min read",
    image: "/images/screenshots/color-1.webp",
    imageAlt: "Color prediction game red green violet interface Pakistan 2026",
  },
];
